apiVersion: v1
kind: Secret
metadata:
  name: vfdvf232323mhjmhjmj3dcscd-secret
  namespace: vfdvf232323mhjmhjmj3dcscd
type: Opaque
data:
  rootpassword: ${{secret.ROOTPASSWORD}} | base64
  userpassword: ${{secret.USERPASSWORD}} | base64
